// Mock data untuk seluruh platform Insight Hub

export const ASSESSMENTS = [
  {
    id: 'love-language',
    title: 'Love Language',
    description: 'Gimana cara kamu ngasih dan nerima kasih sayang?',
    icon: 'Heart',
    duration: '8-10 menit',
    questions: 20,
    category: 'core',
    color: '#0286C3',
    tags: ['komunikasi', 'relasi', 'dasar'],
  },
  {
    id: 'attachment-style',
    title: 'Attachment Style',
    description: 'Pola kelekatan kamu sama orang lain terbentuk dari mana?',
    icon: 'Link',
    duration: '10-12 menit',
    questions: 25,
    category: 'core',
    color: '#17B897',
    tags: ['psikologi', 'pola', 'dasar'],
  },
  {
    id: 'communication-style',
    title: 'Gaya Komunikasi',
    description: 'Kamu lebih suka ngomong langsung atau memutar?',
    icon: 'MessageCircle',
    duration: '6-8 menit',
    questions: 18,
    category: 'communication',
    color: '#F5A623',
    tags: ['komunikasi', 'ekspresi'],
  },
  {
    id: 'emotional-needs',
    title: 'Kebutuhan Emosional',
    description: 'Apa yang kamu butuhkan buat ngerasa aman dan dicintai?',
    icon: 'Shield',
    duration: '8-10 menit',
    questions: 22,
    category: 'emotion',
    color: '#9B59B6',
    tags: ['emosi', 'kebutuhan'],
  },
  {
    id: 'conflict-response',
    title: 'Respons Konflik',
    description: 'Kalau ada masalah, gimana cara kamu nanggepin?',
    icon: 'Zap',
    duration: '7-9 menit',
    questions: 20,
    category: 'conflict',
    color: '#D32F2F',
    tags: ['konflik', 'respons'],
  },
  {
    id: 'trust-style',
    title: 'Gaya Kepercayaan',
    description: 'Seberapa mudah kamu percaya sama orang lain?',
    icon: 'Lock',
    duration: '6-8 menit',
    questions: 16,
    category: 'trust',
    color: '#0073AA',
    tags: ['kepercayaan', 'pola'],
  },
  {
    id: 'boundary-style',
    title: 'Gaya Batasan',
    description: 'Kamu udah bisa set boundary dengan sehat?',
    icon: 'CircleDashed',
    duration: '8-10 menit',
    questions: 20,
    category: 'boundary',
    color: '#17B897',
    tags: ['batasan', 'diri'],
  },
  {
    id: 'stress-response',
    title: 'Respons Stres',
    description: 'Gimana badan dan pikiran kamu ngerespons tekanan?',
    icon: 'Activity',
    duration: '7-8 menit',
    questions: 18,
    category: 'emotion',
    color: '#E67E22',
    tags: ['stres', 'regulasi'],
  },
  {
    id: 'emotional-regulation',
    title: 'Regulasi Emosi',
    description: 'Seberapa baik kamu bisa kelola emosi sendiri?',
    icon: 'Sliders',
    duration: '9-11 menit',
    questions: 22,
    category: 'emotion',
    color: '#8E44AD',
    tags: ['emosi', 'kontrol'],
  },
  {
    id: 'self-awareness',
    title: 'Self-Awareness',
    description: 'Seberapa dalam kamu kenal diri sendiri?',
    icon: 'Eye',
    duration: '10-12 menit',
    questions: 24,
    category: 'self',
    color: '#1ABC9C',
    tags: ['diri', 'kesadaran'],
  },
  {
    id: 'reassurance-needs',
    title: 'Kebutuhan Validasi',
    description: 'Seberapa sering kamu butuh kepastian dari orang lain?',
    icon: 'CheckCircle',
    duration: '6-7 menit',
    questions: 15,
    category: 'emotion',
    color: '#3498DB',
    tags: ['validasi', 'kebutuhan'],
  },
  {
    id: 'vulnerability',
    title: 'Kerentanan',
    description: 'Seberapa nyaman kamu buat jujur dan terbuka?',
    icon: 'Layers',
    duration: '8-9 menit',
    questions: 18,
    category: 'self',
    color: '#E91E63',
    tags: ['keterbukaan', 'keberanian'],
  },
  {
    id: 'active-listening',
    title: 'Active Listening',
    description: 'Kamu dengerin orang lain atau cuma nunggu giliran ngomong?',
    icon: 'Headphones',
    duration: '6-8 menit',
    questions: 16,
    category: 'communication',
    color: '#00BCD4',
    tags: ['mendengar', 'komunikasi'],
  },
  {
    id: 'independence-closeness',
    title: 'Kemandirian vs Kedekatan',
    description: 'Kamu lebih suka sendiri atau selalu bareng?',
    icon: 'ArrowLeftRight',
    duration: '7-8 menit',
    questions: 18,
    category: 'attachment',
    color: '#FF9800',
    tags: ['kemandirian', 'kedekatan'],
  },
  {
    id: 'conflict-repair',
    title: 'Pemulihan Konflik',
    description: 'Gimana cara kamu benerin hubungan setelah ribut?',
    icon: 'RefreshCw',
    duration: '7-9 menit',
    questions: 18,
    category: 'conflict',
    color: '#4CAF50',
    tags: ['rekonsiliasi', 'perbaikan'],
  },
  {
    id: 'consistency-test',
    title: 'Konsistensi',
    description: 'Seberapa bisa kamu diandalkan dalam relasi?',
    icon: 'Calendar',
    duration: '6-7 menit',
    questions: 15,
    category: 'trust',
    color: '#607D8B',
    tags: ['konsisten', 'andalan'],
  },
  {
    id: 'relationship-readiness',
    title: 'Kesiapan Relasi',
    description: 'Siap belum buat hubungan yang sehat dan serius?',
    icon: 'Star',
    duration: '10-12 menit',
    questions: 24,
    category: 'readiness',
    color: '#FF5722',
    tags: ['kesiapan', 'relasi'],
  },
  {
    id: 'indirect-direct-communication',
    title: 'Komunikasi Langsung vs Tidak',
    description: 'Kamu tipe yang to-the-point atau suka basa-basi dulu?',
    icon: 'ArrowRight',
    duration: '5-7 menit',
    questions: 14,
    category: 'communication',
    color: '#795548',
    tags: ['komunikasi', 'gaya'],
  },
  {
    id: 'validation-need',
    title: 'Kebutuhan Pengakuan',
    description: 'Seberapa penting pengakuan orang lain buat kamu?',
    icon: 'Award',
    duration: '6-8 menit',
    questions: 16,
    category: 'emotion',
    color: '#9C27B0',
    tags: ['pengakuan', 'harga-diri'],
  },
]

export const BLOG_POSTS = [
  {
    id: '1',
    title: 'Kenapa Kamu Sering Ghosting? Ini Bukan Tentang Orang Itu',
    slug: 'kenapa-sering-ghosting',
    excerpt: 'Nggak semua orang yang ghosting itu jahat. Kadang itu bentuk self-protection yang belum disadari.',
    category: 'Attachment Style',
    tag: ['attachment', 'avoidant', 'komunikasi'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-20',
    readTime: '5 menit',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    trending: true,
  },
  {
    id: '2',
    title: 'Love Language Kamu Bisa Berubah — Dan Itu Normal',
    slug: 'love-language-bisa-berubah',
    excerpt: 'Dulu words of affirmation paling nendang, sekarang quality time yang bikin kamu ngerasa dicintai. Kenapa bisa gitu?',
    category: 'Love Language',
    tag: ['love-language', 'perubahan', 'diri'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-18',
    readTime: '6 menit',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
    trending: true,
  },
  {
    id: '3',
    title: 'Cara Ngomong yang Bener Saat Kamu Lagi Kesel Banget',
    slug: 'cara-ngomong-saat-kesel',
    excerpt: 'Marah boleh, tapi cara ngomongnya yang nentuin apakah masalah selesai atau makin runyam.',
    category: 'Komunikasi',
    tag: ['konflik', 'komunikasi', 'emosi'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-15',
    readTime: '7 menit',
    coverImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80',
    trending: false,
  },
  {
    id: '4',
    title: 'Tanda Kamu Punya Anxious Attachment (Dan Cara Ngatasinnya)',
    slug: 'tanda-anxious-attachment',
    excerpt: 'Selalu takut ditinggal, sering overthinking, ngerasa nggak pernah cukup? Mungkin ini bukan soal orangnya.',
    category: 'Attachment Style',
    tag: ['anxious', 'attachment', 'self-awareness'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-12',
    readTime: '8 menit',
    coverImage: 'https://images.unsplash.com/photo-1541199249251-f713e6145474?w=800&q=80',
    trending: false,
  },
  {
    id: '5',
    title: 'Mengapa Konflik Bisa Jadi Sehat untuk Hubungan',
    slug: 'konflik-yang-sehat',
    excerpt: 'Bukan berarti harus ribut mulu, tapi konflik yang dikelola dengan baik justru bikin hubungan makin kuat.',
    category: 'Konflik',
    tag: ['konflik', 'relasi', 'komunikasi'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-10',
    readTime: '6 menit',
    coverImage: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?w=800&q=80',
    trending: false,
  },
  {
    id: '6',
    title: 'Passive Aggressive: Diam yang Lebih Menyakitkan dari Kata-kata',
    slug: 'passive-aggressive-explained',
    excerpt: 'Nggak bilang apa-apa tapi mukanya jelas kesel. Ini lebih merusak dari yang kamu kira.',
    category: 'Komunikasi',
    tag: ['pasif-agresif', 'komunikasi', 'konflik'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-08',
    readTime: '5 menit',
    coverImage: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=800&q=80',
    trending: false,
  },
  {
    id: '7',
    title: 'Apa Itu Secure Attachment dan Gimana Cara Ngembanginnya?',
    slug: 'secure-attachment-guide',
    excerpt: 'Secure attachment bukan cuma soal lahir beruntung. Ini skill yang bisa dilatih, bahkan kalau kamu udah trauma.',
    category: 'Attachment Style',
    tag: ['secure', 'attachment', 'healing'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-05',
    readTime: '9 menit',
    coverImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
    trending: true,
  },
  {
    id: '8',
    title: '5 Kalimat yang Tanpa Sadar Bikin Pasangan Ngerasa Nggak Dihargai',
    slug: 'kalimat-bikin-tidak-dihargai',
    excerpt: '"Ah lebay lo." "Udah, nggak usah dipikirin." Kata-kata itu terasa enteng, tapi efeknya bisa bertahan lama banget.',
    category: 'Komunikasi',
    tag: ['validasi', 'kata-kata', 'emosi'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-06-02',
    readTime: '6 menit',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    trending: true,
  },
  {
    id: '9',
    title: 'Kerentanan itu Kekuatan: Belajar Open Up Tanpa Takut Disakitin',
    slug: 'kerentanan-kekuatan',
    excerpt: 'Banyak orang salah kaprah soal kerentanan. Open up bukan berarti lemah — itu malah tanda keberanian.',
    category: 'Self-awareness',
    tag: ['kerentanan', 'kepercayaan', 'intimacy'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-05-28',
    readTime: '7 menit',
    coverImage: 'https://images.unsplash.com/photo-1524168272322-bf73616d9cb5?w=800&q=80',
    trending: false,
  },
  {
    id: '10',
    title: 'Cara Kenali Apakah Kamu Lagi Over-giving dalam Hubungan',
    slug: 'over-giving-dalam-hubungan',
    excerpt: 'Memberikan terlalu banyak sering terasa "baik", tapi kalau kamu selalu yang memberi dan jarang menerima — perlu dicek.',
    category: 'Relasi',
    tag: ['over-giving', 'boundaries', 'reciprocal'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-05-25',
    readTime: '6 menit',
    coverImage: 'https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?w=800&q=80',
    trending: false,
  },
  {
    id: '11',
    title: 'Overthinking di Malam Hari: Ini Bukan Kelemahan, Ini Sinyal',
    slug: 'overthinking-malam-hari',
    excerpt: 'Pikiran yang nggak bisa berhenti di malam hari bukan tanda kamu gila — itu cara otak kamu memproses yang belum selesai.',
    category: 'Emosi',
    tag: ['overthinking', 'kecemasan', 'tidur'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-05-22',
    readTime: '5 menit',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    trending: false,
  },
  {
    id: '12',
    title: 'Gimana Caranya Rebuild Trust Setelah Kepercayaan Rusak?',
    slug: 'rebuild-trust-setelah-rusak',
    excerpt: 'Kepercayaan itu rapuh, tapi bisa dibangun lagi. Prosesnya nggak instan, tapi ada langkah-langkah yang bisa diikuti.',
    category: 'Relasi',
    tag: ['trust', 'pengkhianatan', 'rekonsiliasi'],
    author: { name: 'Tim Insight Hub', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face' },
    publishedAt: '2026-05-18',
    readTime: '8 menit',
    coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
    trending: false,
  },
]

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Rara Setiawan',
    role: 'Mahasiswa S2',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face',
    quote: 'Gue udah coba banyak quiz soal kepribadian, tapi baru Insight Hub yang beneran ngerasa "gue banget". Insightnya daleeem dan nggak judgemental sama sekali.',
    rating: 5,
    plan: 'Premium',
  },
  {
    id: '2',
    name: 'Dimas Pratama',
    role: 'Content Creator',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    quote: 'Chat Analyzer-nya beneran game-changer. Gue paste chat yang bikin gue galau, dan sistemnya langsung detect kenapa vibes-nya nggak enak. Langsung ngerti harus ngomong apa.',
    rating: 5,
    plan: 'Premium',
  },
  {
    id: '3',
    name: 'Kirana Dewi',
    role: 'Psikolog Klinis',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    quote: 'Saya rekomendasikan platform ini ke klien-klien saya sebagai tool self-reflection tambahan. Pendekatannya science-based tapi bahasanya tetap ringan dan nggak bikin takut.',
    rating: 5,
    plan: 'Enterprise',
  },
  {
    id: '4',
    name: 'Bima Ardiansyah',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=80&h=80&fit=crop&crop=face',
    quote: 'Journal di sini bukan sekadar nulis-nulis. Tiap minggu ada pattern insight yang bikin gue sadar kebiasaan komunikasi yang nggak gue sadarin selama ini.',
    rating: 5,
    plan: 'Basic',
  },
  {
    id: '5',
    name: 'Anisa Nurhaliza',
    role: 'UX Designer',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    quote: 'Fitur simulasi percakapannya itu... wow. Latihan ngomong soal topik sensitif sebelum beneran ngobrol sama pasangan. Sangat bantu buat yang struggle ngulangin masalah yang sama.',
    rating: 5,
    plan: 'Couple Plan',
  },
  {
    id: '6',
    name: 'Fajar Nugroho',
    role: 'Entrepreneur',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop&crop=face',
    quote: 'Awalnya skeptis, tapi setelah nyoba assessment lengkap, gue nemu pola di diri sendiri yang gue nggak sadar selama bertahun-tahun. Worth it banget.',
    rating: 5,
    plan: 'Premium',
  },
]

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Gratis',
    price: 0,
    billing: 'Selamanya',
    description: 'Buat kamu yang baru mau mulai kenalan sama diri sendiri.',
    features: [
      'Akses kuis relasi dasar',
      'Mood tracker harian',
      'Insight dasar',
    ],
    notIncluded: [],
    cta: 'Mulai Gratis',
    popular: false,
    color: '#536171',
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 79000,
    billing: '/30 hari',
    description: 'Kalau kamu serius mau ngerti pola diri sendiri lebih dalam.',
    features: [
      'Akses hingga 10 kuis lengkap',
      '10x Chat analyzer relasi',
      'Mood tracker harian',
      'Rujukan saran dasar',
    ],
    notIncluded: [],
    cta: 'Coba 7 Hari Gratis',
    popular: false,
    color: '#0286C3',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 149000,
    billing: '/30 hari',
    description: 'Pengalaman penuh untuk growth yang beneran nendang.',
    features: [
      'Akses penuh 19 kuis',
      'Chat analyzer unlimited',
      'Simulasi percakapan (Teman Curhat & Partner Virtual)',
      'Insight kepribadian mendalam',
      'Export PDF report lengkap',
      'Priority support 24/7',
    ],
    notIncluded: [],
    cta: 'Coba 14 Hari Gratis',
    popular: true,
    color: '#0286C3',
  },
  {
    id: 'couple',
    name: 'Couple Plan',
    price: 229000,
    billing: '/30 hari',
    description: 'Buat kamu dan pasangan yang mau tumbuh bareng.',
    features: [
      'Akses penuh Premium untuk 2 akun',
      'Kuis pasangan khusus (Conflict Response)',
      'Hubungkan akun dengan pasangan',
      'Mood tracker & journal bersama',
      'Chat analyzer unlimited',
      'Priority support 24/7',
    ],
    notIncluded: [],
    cta: 'Mulai Bersama',
    popular: false,
    color: '#E91E63',
  },
]

export const FAQS = [
  {
    id: '1',
    question: 'Platform ini buat siapa?',
    answer: 'Buat siapa aja yang mau lebih ngerti diri sendiri dan pola relasinya — baik yang lagi single, pacaran, menikah, atau habis putus sekalipun. Nggak harus ada masalah dulu buat mulai.',
  },
  {
    id: '2',
    question: 'Apakah hasilnya akurat?',
    answer: 'Insight yang kita kasih didasarkan dari jawaban yang kamu berikan sendiri, bukan tebak-tebakan. Semakin jujur jawaban kamu, semakin relevan insight yang keluar. Dan semua hasil punya confidence score yang transparan.',
  },
  {
    id: '3',
    question: 'Data aku aman nggak di sini?',
    answer: 'Aman. Semua data dienkripsi dan nggak pernah kita jual ke pihak ketiga. Kamu juga bisa hapus semua data kamu kapan aja. Kita nggak main-main soal ini.',
  },
  {
    id: '4',
    question: 'Ini pengganti terapi atau konseling nggak?',
    answer: 'Bukan. Insight Hub adalah alat bantu self-reflection dan awareness — bukan pengganti profesional kesehatan mental. Kalau kamu ngerasa butuh bantuan lebih, kita selalu saranin untuk ke psikolog atau konselor yang tepat.',
  },
  {
    id: '5',
    question: 'Bisa cancel kapan aja nggak?',
    answer: 'Bisa, kapan aja tanpa ribet. Nggak ada hidden fee, nggak ada yang ngebuat kamu ngerasa terjebak. Cancel dari settings, beres.',
  },
  {
    id: '6',
    question: 'Chat Analyzer bisa baca chat dari aplikasi mana aja?',
    answer: 'Kamu bisa paste teks percakapan dari mana aja — WhatsApp, LINE, DM Instagram, iMessage, dll. Cukup copy-paste, sistem kita yang analisis.',
  },
  {
    id: '7',
    question: 'Assessment-nya bisa diulang nggak?',
    answer: 'Bisa. Kamu bisa retake assessment kapan aja. Bahkan direkomendasikan buat ngelacak perubahan pola dari waktu ke waktu. Hasil lama tetap tersimpan buat perbandingan.',
  },
  {
    id: '8',
    question: 'Ada versi buat pasangan atau couple?',
    answer: 'Ada! Couple Plan bisa buat 2 akun sekaligus, dengan fitur khusus kayak shared journal, couple assessment, dan compatibility report.',
  },
]

export const MOCK_USER = {
  id: 'user-1',
  name: 'Kamu',
  email: 'user@example.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=80&h=80&fit=crop&crop=face',
  plan: 'Premium',
  joinedAt: '2026-01-15',
  streak: 12,
  completedAssessments: 8,
  totalJournalEntries: 34,
  mood: 'calm',
  onboarded: true,
}

export const MOCK_MOOD_DATA = [
  { date: '2026-06-17', mood: 'calm', energy: 7, stress: 3, note: 'Hari produktif banget' },
  { date: '2026-06-18', mood: 'anxious', energy: 4, stress: 8, note: 'Overthinking malam ini' },
  { date: '2026-06-19', mood: 'happy', energy: 8, stress: 2, note: 'Quality time sama teman-teman' },
  { date: '2026-06-20', mood: 'neutral', energy: 5, stress: 5, note: '' },
  { date: '2026-06-21', mood: 'frustrated', energy: 3, stress: 9, note: 'Miscommunication yang bikin capek' },
  { date: '2026-06-22', mood: 'calm', energy: 6, stress: 4, note: 'Mulai bisa nge-journal lagi' },
  { date: '2026-06-23', mood: 'hopeful', energy: 7, stress: 3, note: 'Hari ini lebih ringan' },
]

export const MOCK_ASSESSMENT_RESULTS = [
  {
    id: 'r1',
    assessmentId: 'love-language',
    title: 'Love Language',
    completedAt: '2026-06-15',
    scores: {
      wordsOfAffirmation: 72,
      qualityTime: 85,
      actsOfService: 45,
      physicalTouch: 60,
      receivingGifts: 30,
    },
    dominant: 'Quality Time',
    confidenceScore: 88,
    dataQuality: 92,
  },
  {
    id: 'r2',
    assessmentId: 'attachment-style',
    title: 'Attachment Style',
    completedAt: '2026-06-17',
    scores: {
      secure: 48,
      anxious: 72,
      avoidant: 35,
      disorganized: 22,
    },
    dominant: 'Anxious',
    confidenceScore: 82,
    dataQuality: 90,
  },
  {
    id: 'r3',
    assessmentId: 'communication-style',
    title: 'Gaya Komunikasi',
    completedAt: '2026-06-19',
    scores: {
      assertive: 65,
      passive: 40,
      aggressive: 25,
      passiveAggressive: 55,
    },
    dominant: 'Assertive (tapi ada pasif-agresif tersembunyi)',
    confidenceScore: 75,
    dataQuality: 85,
  },
]

export const CASE_STUDIES = [
  {
    id: 'cs1',
    name: 'Mega, 26 tahun',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face',
    title: 'Dari Anxious ke Lebih Sadar Diri dalam 3 Bulan',
    before: 'Sering overthinking, selalu takut pasangan bakal pergi, sering check-in berlebihan.',
    after: 'Lebih bisa kasih ruang, komunikasinya lebih direct, dan nggak lagi ngerasa insecure terus-terusan.',
    duration: '3 bulan',
    features: ['Assessment', 'Journal', 'Chat Analyzer'],
    quote: 'Baru sadar kalau yang gue takutin bukan pasangan gue, tapi pola dari diri gue sendiri.',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
  },
  {
    id: 'cs2',
    name: 'Reza & Dina',
    avatar: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?w=80&h=80&fit=crop&crop=face',
    title: 'Couple yang Belajar Ribut dengan Benar',
    before: 'Konflik berulang soal hal yang sama, satu orang selalu shutdown sementara yang lain terus push.',
    after: 'Udah punya bahasa konflik yang lebih sehat, tau kapan harus berhenti, dan gimana cara repair.',
    duration: '4 bulan',
    features: ['Couple Plan', 'Simulasi', 'Conflict Assessment'],
    quote: 'Ternyata cara kita ribut yang jadi masalah, bukan isi ributnya.',
    coverImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=80',
  },
]

export const HOW_IT_WORKS = [
  {
    step: 1,
    icon: 'ClipboardList',
    title: 'Isi Assessment',
    description: 'Mulai dari assessment yang paling relate sama kondisi kamu sekarang. Nggak perlu semua dulu, pilih yang paling ngena aja.',
    color: '#0286C3',
  },
  {
    step: 2,
    icon: 'BarChart2',
    title: 'Dapet Insight',
    description: 'Sistem kita analisis pola dari jawabanmu dan kasih breakdown yang clear dan nggak judgemental.',
    color: '#17B897',
  },
  {
    step: 3,
    icon: 'BookOpen',
    title: 'Catat & Lacak',
    description: 'Track mood harian, journal kejadian relasi, dan analisis chat yang bikin bingung.',
    color: '#F5A623',
  },
  {
    step: 4,
    icon: 'TrendingUp',
    title: 'Lihat Pola & Tumbuh',
    description: 'Dari waktu ke waktu, kamu bakal lihat pola yang muncul dan bisa mulai ubah yang nggak sehat.',
    color: '#9B59B6',
  },
]

export const FEATURES_HIGHLIGHT = [
  {
    id: 'assessment',
    icon: 'ClipboardList',
    title: '19 Assessment Mendalam',
    description: 'Dari love language sampai attachment style, semuanya saling nyambung dan kasih gambaran utuh tentang kamu.',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80',
    color: '#0286C3',
  },
  {
    id: 'chat-analyzer',
    icon: 'MessageSquare',
    title: 'Chat Analyzer',
    description: 'Paste percakapan yang bikin kamu galau. Kita analisis tone, emosi, dan kasih saran balasan yang lebih sehat.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80',
    color: '#17B897',
  },
  {
    id: 'mood-tracker',
    icon: 'Activity',
    title: 'Mood Tracker Harian',
    description: 'Rekam mood, energi, dan stres setiap hari. Lihat pola yang muncul mingguan dan bulanan.',
    image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&q=80',
    color: '#F5A623',
  },
  {
    id: 'journal',
    icon: 'BookOpen',
    title: 'Jurnal Relasi',
    description: 'Simpan kejadian penting, konflik, rekonsiliasi, dan refleksi pribadi. Semuanya tersimpan rapi dan bisa dicari.',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80',
    color: '#9B59B6',
  },
  {
    id: 'roleplay',
    icon: 'Users',
    title: 'Simulasi Percakapan',
    description: 'Latihan ngobrol tentang topik sensitif sebelum ngelakuinnya di dunia nyata. Ada feedback real-time.',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=80',
    color: '#E91E63',
  },
  {
    id: 'insights',
    icon: 'TrendingUp',
    title: 'Insight & Rekomendasi',
    description: 'Sistem kasih rekomendasi personal berdasarkan kombinasi semua data kamu — bukan cuma quiz.',
    image: 'https://images.unsplash.com/photo-1504596168-46af22a8dcb4?w=600&q=80',
    color: '#00BCD4',
  },
]

export const LOVE_LANGUAGE_QUESTIONS = [
  {
    id: 'q1',
    text: 'Kalau pasangan atau orang penting buat kamu mau bikin kamu ngerasa spesial, yang paling bikin hati lumer itu...',
    options: [
      { id: 'a', text: 'Dia bilang langsung betapa dia hargain kamu', dimension: 'wordsOfAffirmation', weight: 3 },
      { id: 'b', text: 'Dia nyempetin waktu buat nemenin kamu, fokus penuh', dimension: 'qualityTime', weight: 3 },
      { id: 'c', text: 'Dia bantu beresin hal yang bikin kamu repot', dimension: 'actsOfService', weight: 3 },
      { id: 'd', text: 'Dia peluk atau sentuh tangan kamu', dimension: 'physicalTouch', weight: 3 },
      { id: 'e', text: 'Dia bawa sesuatu buat kamu, meski kecil', dimension: 'receivingGifts', weight: 3 },
    ],
  },
  {
    id: 'q2',
    text: 'Saat kamu lagi down atau stres, yang paling kamu butuhin dari orang tersayang adalah...',
    options: [
      { id: 'a', text: 'Dia bilang "aku di sini, aku percaya kamu"', dimension: 'wordsOfAffirmation', weight: 3 },
      { id: 'b', text: 'Dia duduk bareng kamu dan dengerin', dimension: 'qualityTime', weight: 3 },
      { id: 'c', text: 'Dia langsung bantu tanpa perlu diminta', dimension: 'actsOfService', weight: 3 },
      { id: 'd', text: 'Dia peluk kamu sampai kamu lebih tenang', dimension: 'physicalTouch', weight: 3 },
      { id: 'e', text: 'Dia beli makanan favoritmu atau hal yang bikin kamu happy', dimension: 'receivingGifts', weight: 3 },
    ],
  },
  {
    id: 'q3',
    text: 'Kamu ngerasa paling "tidak dihargai" kalau...',
    options: [
      { id: 'a', text: 'Orang jarang atau nggak pernah ngomong terima kasih atau apresiasi', dimension: 'wordsOfAffirmation', weight: 2 },
      { id: 'b', text: 'Kamu selalu ngerasa jadi prioritas yang belakangan', dimension: 'qualityTime', weight: 2 },
      { id: 'c', text: 'Kamu harus lakuin segalanya sendiri tanpa ada yang bantu', dimension: 'actsOfService', weight: 2 },
      { id: 'd', text: 'Kamu ngerasa jauh secara fisik dari orang tersayang', dimension: 'physicalTouch', weight: 2 },
      { id: 'e', text: 'Hari penting kamu diabaikan atau dilupain', dimension: 'receivingGifts', weight: 2 },
    ],
  },
]

export const ATTACHMENT_QUESTIONS = [
  {
    id: 'q1',
    text: 'Kalau orang yang kamu sayang tiba-tiba nggak bales pesan beberapa jam, yang kamu rasain paling duluan...',
    options: [
      { id: 'a', text: 'Biasa aja, pasti lagi sibuk', dimension: 'secure', weight: 3 },
      { id: 'b', text: 'Langsung khawatir, apa ada yang salah?', dimension: 'anxious', weight: 3 },
      { id: 'c', text: 'Nggak terlalu dipikirin, gue juga punya urusan sendiri', dimension: 'avoidant', weight: 3 },
      { id: 'd', text: 'Bingung antara khawatir tapi mau ngilang aja', dimension: 'disorganized', weight: 3 },
    ],
  },
  {
    id: 'q2',
    text: 'Dalam hubungan, kamu cenderung...',
    options: [
      { id: 'a', text: 'Bisa minta tolong dan bisa juga mandiri', dimension: 'secure', weight: 3 },
      { id: 'b', text: 'Selalu ingin tahu posisi kamu di hati orang itu', dimension: 'anxious', weight: 3 },
      { id: 'c', text: 'Lebih nyaman kalau punya ruang sendiri yang cukup', dimension: 'avoidant', weight: 3 },
      { id: 'd', text: 'Pengen dekat tapi nggak tau caranya', dimension: 'disorganized', weight: 3 },
    ],
  },
]

export const CONFLICT_SCENARIOS = [
  {
    id: 'scenario-1',
    title: 'Pasangan Telat Tanpa Kabar',
    description: 'Kamu udah nungguin 2 jam, dan pasangan baru muncul tanpa ngasih kabar sama sekali.',
    systemPersona: 'Kamu adalah pasangan yang baru pulang dan belum tau kenapa lawan bicaramu terlihat kecewa.',
    difficulty: 'Pemula',
    duration: '10-15 menit',
    skills: ['Komunikasi asertif', 'Mengungkapkan perasaan tanpa menyalahkan'],
    color: '#F5A623',
  },
  {
    id: 'scenario-2',
    title: 'Perlu Ngomong Soal Batasan',
    description: 'Ada satu kebiasaan orang terdekat yang udah lama ganggu kamu, dan kamu mau ngomong dengan baik.',
    systemPersona: 'Kamu adalah orang yang kebiasaannya akan dibahas. Kamu belum tau apa masalahnya.',
    difficulty: 'Menengah',
    duration: '15-20 menit',
    skills: ['Menyampaikan batasan', 'Assertiveness', 'Mendengar aktif'],
    color: '#0286C3',
  },
  {
    id: 'scenario-3',
    title: 'Konflik yang Berulang',
    description: 'Kalian ribut soal masalah yang sama untuk yang kesekian kalinya. Kamu mau coba selesaikan secara beda.',
    systemPersona: 'Kamu adalah pihak yang sudah frustrasi dengan pola yang berulang ini.',
    difficulty: 'Lanjutan',
    duration: '20-25 menit',
    skills: ['Conflict repair', 'Pattern recognition', 'Rekonsiliasi'],
    color: '#D32F2F',
  },
]
